In [1]:
# Import basic libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
df1 = pd.read_excel("dataset1.xlsx")
df2 = pd.read_excel("dataset2.xlsx")

In [3]:
df1.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.0,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32

In [4]:
df2.head()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1

In [5]:
# Load the description file
description_df = pd.read_excel("/content/Description.xlsx")

# Display the content of the description file
display(description_df)

,Case_study1 table,Variable Name,Description
0,Internal,Total_TL,Total trade lines/accounts in Bureau
1,NaN,Tot_Closed_TL,Total closed trade lines/accounts
2,NaN,Tot_Active_TL,Total active accounts
3,NaN,Total_TL_opened_L6M,Total accounts opened in last 6 Months
4,NaN,Tot_TL_closed_L6M,Total accounds closes in last 6 months
...,...,...,...
83,NaN,GL_Flag,Gold Loan Flag
84,NaN,last_prod_enq2,Lates product enquired for
85,NaN,first_prod_enq2,First productd enquired for
86,NaN,Credit_Score,Applicant's credit score
87,NaN,Approved_Flag,Priority levels

In [6]:
df1.shape

(51336, 26)

In [7]:
df2.shape

(51336, 62)

In [8]:
40/51336*100

0.07791803023219572

In [9]:
df1 = df1.loc[df1['Age_Oldest_TL'] != -99999]
df1.shape

(51296, 26)

In [10]:
51336*25/100

12834.0

In [11]:
columns_to_be_removed = []

for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 12834:
        columns_to_be_removed.append(i)

In [12]:
pd.DataFrame(columns_to_be_removed)

                              0
0   time_since_first_deliquency
1  time_since_recent_deliquency
2         max_delinquency_level
3                max_deliq_6mts
4                CC_utilization
5                PL_utilization
6      max_unsec_exposure_inPct

In [13]:
df2 = df2.drop(columns_to_be_removed, axis=1)
df2.shape

(51336, 55)

In [14]:
# KNN imputation method to handle missing data (-99999)

In [15]:
df3 = df2.copy()

In [16]:
for i in df3.columns:
    df3 = df3.loc[df3[i] !=-99999]

In [17]:
df3.shape

(35579, 55)

In [18]:
# common columns name
for i in list(df1.columns):
    if i in list(df3.columns):
        print(i)

PROSPECTID

In [19]:
# Merge both the table basis inner join
df = pd.merge(df1, df3, how='inner', left_on=['PROSPECTID'], right_on = ['PROSPECTID'])

In [20]:
df.shape

(35579, 80)

In [21]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
1,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
2,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
3,8,6,4,2,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,676,P2
4,9,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,658,P4

In [22]:
df.isnull().sum().sum()

np.int64(0)

In [23]:
# Check categorical variable
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [24]:
# Chi-Square Test
from scipy.stats import chi2_contingency

In [25]:
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval,_,_ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 4.095160473208429e-191
EDUCATION --- 2.104715600708518e-37
GENDER --- 6.462836948408467e-06
last_prod_enq2 --- 0.0
first_prod_enq2 --- 1.0235474613330158e-227

In [26]:
# Check numerical columns
numeric_columns = []

for i in df.columns:
    if df[i].dtype !='object' and i not in ['PROSPECTID', 'Approved_Flag']:
        numeric_columns.append(i)

In [27]:
numeric_columns

['Total_TL',
 'Tot_Closed_TL',
 'Tot_Active_TL',
 'Total_TL_opened_L6M',
 'Tot_TL_closed_L6M',
 'pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'pct_active_tl',
 'pct_closed_tl',
 'Total_TL_opened_L12M',
 'Tot_TL_closed_L12M',
 'pct_tl_open_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'Auto_TL',
 'CC_TL',
 'Consumer_TL',
 'Gold_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'num_times_delinquent',
 'max_recent_level_of_deliq',
 'num_deliq_6mts',
 'num_deliq_12mts',
 'num_deliq_6_12mts',
 'max_deliq_12mts',
 'num_times_30p_dpd',
 'num_times_60p_dpd',
 'num_std',
 'num_std_6mts',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_6mts',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_6mts',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'tot_enq',
 'CC_enq',
 'CC_enq_L6m',
 'CC_enq_L12m',
 'PL_enq',
 'PL_enq_L6m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L12m',
 'enq_L6m',
 'enq_L3m',
 'AGE',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'pct_of_active_TLs_ever',
 'pct_opened_TLs_L6m_of_L12m',
 'pct_currentBal_all_TL',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_L12m',
 'pct_CC_enq_L6m_of_L12m',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag',
 'Credit_Score']

In [28]:
# Variance inflation factor
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [29]:
vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0

In [30]:
vif_data.shape

(35579, 73)

In [31]:
for i in range(0, total_columns):
    vif_value = variance_inflation_factor(vif_data, column_index)
    print(column_index, '----', vif_value)

    if vif_value <=6:
        columns_to_be_kept.append(numeric_columns[i])
        column_index = column_index+1
    else:
        vif_data = vif_data.drop([numeric_columns[i]], axis=1)

0 ---- inf
0 ---- inf
0 ---- 11.438786902363596
0 ---- 8.20585760426891
0 ---- 6.548128968896226
0 ---- 5.150257269314183
1 ---- 2.634012466172554
2 ---- inf
2 ---- 1662.6815494654013
2 ---- 8.955702441486007
2 ---- 4.0283593414666505
3 ---- 7.381800402544994
3 ---- 7.234849457263119
3 ---- 2.0456610006584803
4 ---- inf
4 ---- 4.905295045854351
5 ---- 25.052698769699386
5 ---- 29.112471753470423
5 ---- 4.303762283152018
6 ---- 3.0361711215064444
7 ---- 2.854104662594494
8 ---- 4.369960517199508
9 ---- 2.2710713978295773
10 ---- 4.513889995923768
11 ---- 4.0241791097075765
12 ---- 1.8537074096180808
13 ---- 8.429603352270776
13 ---- 4.489624552956796
14 ---- inf
14 ---- 7.803319939469136
14 ---- 1.75303856276489
15 ---- 2.305908965839313
16 ---- 7.932948245852622
16 ---- 1.735140196577847
17 ---- 7.174571981093047
17 ---- 15.045870499301447
17 ---- 1.8154033424603908
18 ---- 1.562191984404212
19 ---- 2.3610950219216136
20 ---- 2.883589955888552
21 ---- 2.1343074876867068
22 ---- 7.322608094013198
22 ---- 1.9523240923540826
23 ---- 1.4997662593404515
24 ---- 2.2072252129112395
25 ---- 2.6620502460079365
26 ---- 4.522611129363697
27 ---- 16.936674595351423
27 ---- 6.560710562750573
27 ---- 8.953712334132254
27 ---- 2.4001247655579085
28 ---- 8.927959220101341
28 ---- 13.217268909412109
28 ---- 3.5517584894290724
29 ---- 2.035377183245419
30 ---- 17.59698718533055
30 ---- 10.808579871160255
30 ---- 2.3980826361072367
31 ---- 22.11546824045451
31 ---- 2.666923962702881
32 ---- 3.414435900620522
33 ---- 10.651588124871125
33 ---- 6.803380345984767
33 ---- 1.0026142971461878
34 ---- 3.090360754579815
35 ---- 2.806742016766425
36 ---- 20.051389542378324
36 ---- 15.597122276269772
36 ---- 1.8657391488648454
37 ---- 1.5762467175055128
38 ---- 1.9465849183379111
39 ---- 4.250510966285353
40 ---- 9.730408334693593

In [32]:
len(columns_to_be_kept)

40

In [33]:
# For numerical - we have to use ANOVA Test
from scipy.stats import f_oneway

In [34]:
columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df['Approved_Flag'])

    group_p1 = [value for value, group in zip(a,b) if group=='P1']
    group_p2 = [value for value, group in zip(a,b) if group=='P2']
    group_p3 = [value for value, group in zip(a,b) if group=='P3']
    group_p4 = [value for value, group in zip(a,b) if group=='P4']

    f_statistic, p_value = f_oneway(group_p1, group_p2, group_p3, group_p4)
    if p_value <=0.05:
        columns_to_be_kept_numerical.append(i)

In [35]:
len(columns_to_be_kept_numerical)

38

In [36]:
columns_to_be_kept_numerical

['pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'Tot_TL_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'max_deliq_12mts',
 'num_times_60p_dpd',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'CC_enq_L12m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag']

In [37]:
# Final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']

In [38]:
df = df[features + ['Approved_Flag']]

In [39]:
df.shape

(35579, 44)

In [40]:
# 'MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'
df['MARITALSTATUS'].unique()

array(['Single', 'Married'], dtype=object)

In [41]:
df['EDUCATION'].unique()

array(['GRADUATE', 'SSC', '12TH', 'UNDER GRADUATE', 'POST-GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

In [42]:
df.loc[df['EDUCATION']=='SSC',['EDUCATION']] = 1
df.loc[df['EDUCATION']=='12TH',['EDUCATION']] = 2
df.loc[df['EDUCATION']=='UNDER GRADUATE',['EDUCATION']] = 3
df.loc[df['EDUCATION']=='GRADUATE',['EDUCATION']] = 3
df.loc[df['EDUCATION']=='POST-GRADUATE',['EDUCATION']] = 4
df.loc[df['EDUCATION']=='PROFESSIONAL',['EDUCATION']] = 3
df.loc[df['EDUCATION']=='OTHERS',['EDUCATION']] = 1

In [43]:
df['EDUCATION'].value_counts()

EDUCATION
3    16172
2     9756
1     8047
4     1604
Name: count, dtype: int64

In [44]:
df['EDUCATION'] = df['EDUCATION'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35579 entries, 0 to 35578
Data columns (total 44 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            35579 non-null  float64
 1   pct_tl_closed_L6M          35579 non-null  float64
 2   Tot_TL_closed_L12M         35579 non-null  int64
 3   Tot_Missed_Pmnt            35579 non-null  int64
 4   CC_TL                      35579 non-null  int64
 5   Home_TL                    35579 non-null  int64
 6   PL_TL                      35579 non-null  int64
 7   Secured_TL                 35579 non-null  int64
 8   Unsecured_TL               35579 non-null  int64
 9   Other_TL                   35579 non-null  int64
 10  Age_Oldest_TL              35579 non-null  int64
 11  Age_Newest_TL              35579 non-null  int64
 12  time_since_recent_payment  35579 non-null  int64
 13  max_recent_level_of_deliq  35579 non-null  int64
 14  num_deliq_6_12mts          35579 non-null  int64
 15  max_deliq_12mts            35579 non-null  int64
 16  num_times_60p_dpd          35579 non-null  int64
 17  num_std_12mts              35579 non-null  int64
 18  num_sub                    35579 non-null  int64
 19  num_sub_6mts               35579 non-null  int64
 20  num_sub_12mts              35579 non-null  int64
 21  num_dbt                    35579 non-null  int64
 22  num_dbt_12mts              35579 non-null  int64
 23  num_lss                    35579 non-null  int64
 24  num_lss_12mts              35579 non-null  int64
 25  recent_level_of_deliq      35579 non-null  int64
 26  CC_enq_L12m                35579 non-null  int64
 27  PL_enq_L12m                35579 non-null  int64
 28  time_since_recent_enq      35579 non-null  int64
 29  enq_L3m                    35579 non-null  int64
 30  NETMONTHLYINCOME           35579 non-null  int64
 31  Time_With_Curr_Empr        35579 non-null  int64
 32  CC_Flag                    35579 non-null  int64
 33  PL_Flag                    35579 non-null  int64
 34  pct_PL_enq_L6m_of_ever     35579 non-null  float64
 35  pct_CC_enq_L6m_of_ever     35579 non-null  float64
 36  HL_Flag                    35579 non-null  int64
 37  GL_Flag                    35579 non-null  int64
 38  MARITALSTATUS              35579 non-null  object
 39  EDUCATION                  35579 non-null  int64
 40  GENDER                     35579 non-null  object
 41  last_prod_enq2             35579 non-null  object
 42  first_prod_enq2            35579 non-null  object
 43  Approved_Flag              35579 non-null  object
dtypes: float64(4), int64(35), object(5)
memory usage: 11.9+ MB

In [45]:
df['GENDER'].unique()

array(['F', 'M'], dtype=object)

In [46]:
df['last_prod_enq2'].unique()

array(['ConsumerLoan', 'CC', 'others', 'PL', 'HL', 'AL'], dtype=object)

In [47]:
df['first_prod_enq2'].unique()

array(['ConsumerLoan', 'others', 'PL', 'HL', 'CC', 'AL'], dtype=object)

In [48]:
df_encoded = pd.get_dummies(df, columns=['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2'])

In [49]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35579 entries, 0 to 35578
Data columns (total 56 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               35579 non-null  float64
 1   pct_tl_closed_L6M             35579 non-null  float64
 2   Tot_TL_closed_L12M            35579 non-null  int64
 3   Tot_Missed_Pmnt               35579 non-null  int64
 4   CC_TL                         35579 non-null  int64
 5   Home_TL                       35579 non-null  int64
 6   PL_TL                         35579 non-null  int64
 7   Secured_TL                    35579 non-null  int64
 8   Unsecured_TL                  35579 non-null  int64
 9   Other_TL                      35579 non-null  int64
 10  Age_Oldest_TL                 35579 non-null  int64
 11  Age_Newest_TL                 35579 non-null  int64
 12  time_since_recent_payment     35579 non-null  int64
 13  max_recent_level_of_deliq     35579 non-null  int64
 14  num_deliq_6_12mts             35579 non-null  int64
 15  max_deliq_12mts               35579 non-null  int64
 16  num_times_60p_dpd             35579 non-null  int64
 17  num_std_12mts                 35579 non-null  int64
 18  num_sub                       35579 non-null  int64
 19  num_sub_6mts                  35579 non-null  int64
 20  num_sub_12mts                 35579 non-null  int64
 21  num_dbt                       35579 non-null  int64
 22  num_dbt_12mts                 35579 non-null  int64
 23  num_lss                       35579 non-null  int64
 24  num_lss_12mts                 35579 non-null  int64
 25  recent_level_of_deliq         35579 non-null  int64
 26  CC_enq_L12m                   35579 non-null  int64
 27  PL_enq_L12m                   35579 non-null  int64
 28  time_since_recent_enq         35579 non-null  int64
 29  enq_L3m                       35579 non-null  int64
 30  NETMONTHLYINCOME              35579 non-null  int64
 31  Time_With_Curr_Empr           35579 non-null  int64
 32  CC_Flag                       35579 non-null  int64
 33  PL_Flag                       35579 non-null  int64
 34  pct_PL_enq_L6m_of_ever        35579 non-null  float64
 35  pct_CC_enq_L6m_of_ever        35579 non-null  float64
 36  HL_Flag                       35579 non-null  int64
 37  GL_Flag                       35579 non-null  int64
 38  EDUCATION                     35579 non-null  int64
 39  Approved_Flag                 35579 non-null  object
 40  MARITALSTATUS_Married         35579 non-null  bool
 41  MARITALSTATUS_Single          35579 non-null  bool
 42  GENDER_F                      35579 non-null  bool
 43  GENDER_M                      35579 non-null  bool
 44  last_prod_enq2_AL             35579 non-null  bool
 45  last_prod_enq2_CC             35579 non-null  bool
 46  last_prod_enq2_ConsumerLoan   35579 non-null  bool
 47  last_prod_enq2_HL             35579 non-null  bool
 48  last_prod_enq2_PL             35579 non-null  bool
 49  last_prod_enq2_others         35579 non-null  bool
 50  first_prod_enq2_AL            35579 non-null  bool
 51  first_prod_enq2_CC            35579 non-null  bool
 52  first_prod_enq2_ConsumerLoan  35579 non-null  bool
 53  first_prod_enq2_HL            35579 non-null  bool
 54  first_prod_enq2_PL            35579 non-null  bool
 55  first_prod_enq2_others        35579 non-null  bool
dtypes: bool(16), float64(4), int64(35), object(1)
memory usage: 11.4+ MB

In [50]:
k = df_encoded.describe()

In [51]:
k

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,...,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,EDUCATION
count,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,...,35579.000000,3.557900e+04,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000
mean,0.200989,0.109181,0.938110,0.592119,0.170831,0.080666,0.349785,2.993564,2.659996,1.188370,...,1.308890,2.723659e+04,108.906490,0.120183,0.206217,0.211490,0.071921,0.245117,0.059867,2.318531
std,0.284536,0.217417,1.620181,1.159504,0.592211,0.369539,0.946365,6.558166,3.579309,2.594753,...,2.175757,2.187316e+04,74.565352,0.325180,0.404594,0.376545,0.237500,0.430162,0.237243,0.871551
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,1.800000e+04,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,...,1.000000,2.450000e+04,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,0.333000,0.143000,1.000000,1.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,...,2.000000,3.200000e+04,131.000000,0.000000,0.000000,0.333000,0.000000,0.000000,0.000000,3.000000
max,1.000000,1.000000,33.000000,34.000000,27.000000,10.000000,29.000000,235.000000,55.000000,80.000000,...,42.000000,2.500000e+06,1020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [52]:
df_encoded = df_encoded.drop(['MARITALSTATUS_Married','GENDER_F','last_prod_enq2_AL', 'first_prod_enq2_AL'], axis=1)

In [53]:
df_encoded.shape

(35579, 52)

In [54]:
df_encoded.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,...,last_prod_enq2_CC,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others
0,0.000,0.0,0,0,0,0,0,0,1,0,...,False,True,False,False,False,False,True,False,False,False
1,0.125,0.0,0,1,0,0,0,2,6,0,...,False,True,False,False,False,False,False,False,False,True
2,0.000,0.0,1,0,0,0,0,6,0,0,...,False,True,False,False,False,False,False,False,True,False
3,0.000,0.0,2,0,0,0,0,6,0,5,...,False,True,False,False,False,False,False,False,False,True
4,0.000,0.0,0,0,0,0,0,1,0,0,...,False,True,False,False,False,False,False,False,False,True

In [55]:
df_encoded.describe()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,...,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,EDUCATION
count,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,...,35579.000000,3.557900e+04,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000,35579.000000
mean,0.200989,0.109181,0.938110,0.592119,0.170831,0.080666,0.349785,2.993564,2.659996,1.188370,...,1.308890,2.723659e+04,108.906490,0.120183,0.206217,0.211490,0.071921,0.245117,0.059867,2.318531
std,0.284536,0.217417,1.620181,1.159504,0.592211,0.369539,0.946365,6.558166,3.579309,2.594753,...,2.175757,2.187316e+04,74.565352,0.325180,0.404594,0.376545,0.237500,0.430162,0.237243,0.871551
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,1.800000e+04,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,...,1.000000,2.450000e+04,90.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,0.333000,0.143000,1.000000,1.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,...,2.000000,3.200000e+04,131.000000,0.000000,0.000000,0.333000,0.000000,0.000000,0.000000,3.000000
max,1.000000,1.000000,33.000000,34.000000,27.000000,10.000000,29.000000,235.000000,55.000000,80.000000,...,42.000000,2.500000e+06,1020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [56]:
df_encoded.isnull().sum().sum()

np.int64(0)

In [57]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35579 entries, 0 to 35578
Data columns (total 52 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               35579 non-null  float64
 1   pct_tl_closed_L6M             35579 non-null  float64
 2   Tot_TL_closed_L12M            35579 non-null  int64
 3   Tot_Missed_Pmnt               35579 non-null  int64
 4   CC_TL                         35579 non-null  int64
 5   Home_TL                       35579 non-null  int64
 6   PL_TL                         35579 non-null  int64
 7   Secured_TL                    35579 non-null  int64
 8   Unsecured_TL                  35579 non-null  int64
 9   Other_TL                      35579 non-null  int64
 10  Age_Oldest_TL                 35579 non-null  int64
 11  Age_Newest_TL                 35579 non-null  int64
 12  time_since_recent_payment     35579 non-null  int64
 13  max_recent_level_of_deliq     35579 non-null  int64
 14  num_deliq_6_12mts             35579 non-null  int64
 15  max_deliq_12mts               35579 non-null  int64
 16  num_times_60p_dpd             35579 non-null  int64
 17  num_std_12mts                 35579 non-null  int64
 18  num_sub                       35579 non-null  int64
 19  num_sub_6mts                  35579 non-null  int64
 20  num_sub_12mts                 35579 non-null  int64
 21  num_dbt                       35579 non-null  int64
 22  num_dbt_12mts                 35579 non-null  int64
 23  num_lss                       35579 non-null  int64
 24  num_lss_12mts                 35579 non-null  int64
 25  recent_level_of_deliq         35579 non-null  int64
 26  CC_enq_L12m                   35579 non-null  int64
 27  PL_enq_L12m                   35579 non-null  int64
 28  time_since_recent_enq         35579 non-null  int64
 29  enq_L3m                       35579 non-null  int64
 30  NETMONTHLYINCOME              35579 non-null  int64
 31  Time_With_Curr_Empr           35579 non-null  int64
 32  CC_Flag                       35579 non-null  int64
 33  PL_Flag                       35579 non-null  int64
 34  pct_PL_enq_L6m_of_ever        35579 non-null  float64
 35  pct_CC_enq_L6m_of_ever        35579 non-null  float64
 36  HL_Flag                       35579 non-null  int64
 37  GL_Flag                       35579 non-null  int64
 38  EDUCATION                     35579 non-null  int64
 39  Approved_Flag                 35579 non-null  object
 40  MARITALSTATUS_Single          35579 non-null  bool
 41  GENDER_M                      35579 non-null  bool
 42  last_prod_enq2_CC             35579 non-null  bool
 43  last_prod_enq2_ConsumerLoan   35579 non-null  bool
 44  last_prod_enq2_HL             35579 non-null  bool
 45  last_prod_enq2_PL             35579 non-null  bool
 46  last_prod_enq2_others         35579 non-null  bool
 47  first_prod_enq2_CC            35579 non-null  bool
 48  first_prod_enq2_ConsumerLoan  35579 non-null  bool
 49  first_prod_enq2_HL            35579 non-null  bool
 50  first_prod_enq2_PL            35579 non-null  bool
 51  first_prod_enq2_others        35579 non-null  bool
dtypes: bool(12), float64(4), int64(35), object(1)
memory usage: 11.3+ MB

In [58]:
bool_columns = ['MARITALSTATUS_Single','GENDER_M','last_prod_enq2_CC','last_prod_enq2_ConsumerLoan','last_prod_enq2_HL',
                'last_prod_enq2_PL','last_prod_enq2_others','first_prod_enq2_CC','first_prod_enq2_ConsumerLoan',
                'first_prod_enq2_HL','first_prod_enq2_PL','first_prod_enq2_others']
bool_columns

['MARITALSTATUS_Single',
 'GENDER_M',
 'last_prod_enq2_CC',
 'last_prod_enq2_ConsumerLoan',
 'last_prod_enq2_HL',
 'last_prod_enq2_PL',
 'last_prod_enq2_others',
 'first_prod_enq2_CC',
 'first_prod_enq2_ConsumerLoan',
 'first_prod_enq2_HL',
 'first_prod_enq2_PL',
 'first_prod_enq2_others']

In [59]:
df_encoded[bool_columns] = df_encoded[bool_columns].astype(float)
print(df_encoded[bool_columns].dtypes)

MARITALSTATUS_Single            float64
GENDER_M                        float64
last_prod_enq2_CC               float64
last_prod_enq2_ConsumerLoan     float64
last_prod_enq2_HL               float64
last_prod_enq2_PL               float64
last_prod_enq2_others           float64
first_prod_enq2_CC              float64
first_prod_enq2_ConsumerLoan    float64
first_prod_enq2_HL              float64
first_prod_enq2_PL              float64
first_prod_enq2_others          float64
dtype: object

In [60]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35579 entries, 0 to 35578
Data columns (total 52 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               35579 non-null  float64
 1   pct_tl_closed_L6M             35579 non-null  float64
 2   Tot_TL_closed_L12M            35579 non-null  int64
 3   Tot_Missed_Pmnt               35579 non-null  int64
 4   CC_TL                         35579 non-null  int64
 5   Home_TL                       35579 non-null  int64
 6   PL_TL                         35579 non-null  int64
 7   Secured_TL                    35579 non-null  int64
 8   Unsecured_TL                  35579 non-null  int64
 9   Other_TL                      35579 non-null  int64
 10  Age_Oldest_TL                 35579 non-null  int64
 11  Age_Newest_TL                 35579 non-null  int64
 12  time_since_recent_payment     35579 non-null  int64
 13  max_recent_level_of_deliq     35579 non-null  int64
 14  num_deliq_6_12mts             35579 non-null  int64
 15  max_deliq_12mts               35579 non-null  int64
 16  num_times_60p_dpd             35579 non-null  int64
 17  num_std_12mts                 35579 non-null  int64
 18  num_sub                       35579 non-null  int64
 19  num_sub_6mts                  35579 non-null  int64
 20  num_sub_12mts                 35579 non-null  int64
 21  num_dbt                       35579 non-null  int64
 22  num_dbt_12mts                 35579 non-null  int64
 23  num_lss                       35579 non-null  int64
 24  num_lss_12mts                 35579 non-null  int64
 25  recent_level_of_deliq         35579 non-null  int64
 26  CC_enq_L12m                   35579 non-null  int64
 27  PL_enq_L12m                   35579 non-null  int64
 28  time_since_recent_enq         35579 non-null  int64
 29  enq_L3m                       35579 non-null  int64
 30  NETMONTHLYINCOME              35579 non-null  int64
 31  Time_With_Curr_Empr           35579 non-null  int64
 32  CC_Flag                       35579 non-null  int64
 33  PL_Flag                       35579 non-null  int64
 34  pct_PL_enq_L6m_of_ever        35579 non-null  float64
 35  pct_CC_enq_L6m_of_ever        35579 non-null  float64
 36  HL_Flag                       35579 non-null  int64
 37  GL_Flag                       35579 non-null  int64
 38  EDUCATION                     35579 non-null  int64
 39  Approved_Flag                 35579 non-null  object
 40  MARITALSTATUS_Single          35579 non-null  float64
 41  GENDER_M                      35579 non-null  float64
 42  last_prod_enq2_CC             35579 non-null  float64
 43  last_prod_enq2_ConsumerLoan   35579 non-null  float64
 44  last_prod_enq2_HL             35579 non-null  float64
 45  last_prod_enq2_PL             35579 non-null  float64
 46  last_prod_enq2_others         35579 non-null  float64
 47  first_prod_enq2_CC            35579 non-null  float64
 48  first_prod_enq2_ConsumerLoan  35579 non-null  float64
 49  first_prod_enq2_HL            35579 non-null  float64
 50  first_prod_enq2_PL            35579 non-null  float64
 51  first_prod_enq2_others        35579 non-null  float64
dtypes: float64(16), int64(35), object(1)
memory usage: 14.1+ MB

In [61]:
df_encoded['Approved_Flag'].value_counts(normalize=True)

Approved_Flag
P2    0.600579
P3    0.160488
P4    0.133674
P1    0.105259
Name: proportion, dtype: float64

In [62]:
# Split the data into dependent and independent variable
x = df_encoded.drop(columns=['Approved_Flag'], axis=1)
y = df_encoded['Approved_Flag']

In [64]:
# SMOTE
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.ensemble import RandomForestClassifier

In [65]:
# SMOTE
smote = SMOTE(random_state=101)
x_smote, y_smote = smote.fit_resample(x, y)
print("after smote, class distribution is:")
print(pd.Series(y_smote).value_counts(normalize=True))

after smote, class distribution is:
Approved_Flag
P2    0.25
P3    0.25
P4    0.25
P1    0.25
Name: proportion, dtype: float64

In [66]:
# RandomOverSampler
randomoversampler = RandomOverSampler(random_state=101)
x_smote, y_smote = randomoversampler.fit_resample(x, y)
print("after smote, class distribution is:")
print(pd.Series(y_smote).value_counts(normalize=True))

after smote, class distribution is:
Approved_Flag
P2    0.25
P3    0.25
P4    0.25
P1    0.25
Name: proportion, dtype: float64

In [67]:
# RandomUnderSampler
randomundersampler = RandomUnderSampler(random_state=101)
x_smote, y_smote = randomundersampler.fit_resample(x, y)
print("after smote, class distribution is:")
print(pd.Series(y_smote).value_counts(normalize=True))

after smote, class distribution is:
Approved_Flag
P1    0.25
P2    0.25
P3    0.25
P4    0.25
Name: proportion, dtype: float64

In [69]:
# Split the data into dependent and independent variable
x = df_encoded.drop(columns=['Approved_Flag'], axis=1)
y = df_encoded['Approved_Flag']

In [70]:
y

0        P2
1        P2
2        P3
3        P2
4        P4
         ..
35574    P2
35575    P4
35576    P1
35577    P3
35578    P2
Name: Approved_Flag, Length: 35579, dtype: object

In [71]:
# Split the data into training and testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101, stratify=y)

# 1. RandomForest Classifier

In [72]:
from sklearn import metrics
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

rf_classifier = RandomForestClassifier(n_estimators=200, random_state=101)
rf_classifier.fit(x_train, y_train)
y_pred = rf_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print()
print(f"Accuracy : {accuracy}")
print()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v} :")
    print(f"Precision : {precision[i]}")
    print(f"Recall : {recall[i]}")
    print(f"F1_Score : {f1_score[i]}")
    print()

Accuracy : 0.771079258010118

Class p1 :
Precision : 0.8361408882082695
Recall : 0.7289719626168224
F1_Score : 0.7788873038516405

Class p2 :
Precision : 0.8029270248596632
Recall : 0.9370613008890969
F1_Score : 0.8648240120924207

Class p3 :
Precision : 0.462406015037594
Recall : 0.21541155866900175
F1_Score : 0.2939068100358423

Class p4 :
Precision : 0.7317073170731707
Recall : 0.7255520504731862
F1_Score : 0.7286166842661035

# 2. xgboost model

In [73]:
from sklearn import metrics
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax', num_class=4)

x = df_encoded.drop(columns=['Approved_Flag'], axis=1)
y = df_encoded['Approved_Flag']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=101, stratify=y)

xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print()
print(f"Accuracy : {accuracy}")
print()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)
#classification_report = classification_report(y_test, y_pred)
#print(f"classification_report : {classification_report}")

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v} :")
    print(f"Precision : {precision[i]}")
    print(f"Recall : {recall[i]}")
    print(f"F1_Score : {f1_score[i]}")
    print()

Accuracy : 0.7774030354131535

Class p1 :
Precision : 0.79702300405954
Recall : 0.7863818424566088
F1_Score : 0.7916666666666666

Class p2 :
Precision : 0.8311328790459966
Recall : 0.9131960692559663
F1_Score : 0.8702341137123746

Class p3 :
Precision : 0.45970937912813736
Recall : 0.30472854640980734
F1_Score : 0.3665086887835703

Class p4 :
Precision : 0.7489177489177489
Recall : 0.7276550998948476
F1_Score : 0.7381333333333333

# Hyperparameter tuning in xgboost

In [74]:
from sklearn.model_selection import GridSearchCV

In [75]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=101, stratify=y)

xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=4)

param_grid = {'n_estimators':[50,100,200],'max_depth':[3,5,7],'learning_rate':[0.01,0.1,0.2],}
grid_search = GridSearchCV(estimator=xgb_model,param_grid=param_grid, cv=5, scoring='accuracy',n_jobs=-1)
grid_search.fit(x_train, y_train)

print("Best Hyperparameters :",grid_search.best_params_)

best_model = grid_search.best_estimator_

accuracy = best_model.score(x_test, y_test)
print("Test Accuracy :", accuracy)

Best Hyperparameters : {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}
Test Accuracy : 0.7880831928049467

# Deep Neural Network - ANN/MLP(multilayer perceptron)

In [76]:
# Mandatory Preprocessing - Feature Scaling
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

x = df_encoded.drop(columns=['Approved_Flag'], axis=1)
y = df_encoded['Approved_Flag']

y_encoded = pd.get_dummies(y).values

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=101, stratify=y)

# Feature Scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# Building Model
model = Sequential()
model.add(Dense(64, input_dim=x_train.shape[1], activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(y_train.shape[1], activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
early_stopping = EarlyStopping(monitor='val_loss',patience=10, restore_best_weights=True)

history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100, batch_size=32, callbacks=[early_stopping])
# Evaluate the model
y_pred_prob = model.predict(x_test)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true = np.argmax(y_test, axis=1)

print(classification_report(y_true, y_pred, target_names=['P1', 'P2', 'P3', 'P4']))

Epoch 1/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.6650 - loss: 0.8437 - val_accuracy: 0.7551 - val_loss: 0.5981
Epoch 2/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7549 - loss: 0.5930 - val_accuracy: 0.7632 - val_loss: 0.5604
Epoch 3/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7635 - loss: 0.5547 - val_accuracy: 0.7669 - val_loss: 0.5420
Epoch 4/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7725 - loss: 0.5321 - val_accuracy: 0.7621 - val_loss: 0.5318
Epoch 5/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7690 - loss: 0.5251 - val_accuracy: 0.7709 - val_loss: 0.5290
Epoch 6/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7806 - loss: 0.5054 - val_accuracy: 0.7736 - val_loss: 0.5320
Epoch 7/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7803 - loss: 0.5041 - val_accuracy: 0.7730 - val_loss: 0.5178
Epoch 8/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7803 - loss: 0.5010 - val_accuracy: 0.7740 - val_loss: 0.5161
Epoch 9/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7843 - loss: 0.4853 - val_accuracy: 0.7736 - val_loss: 0.5137
Epoch 10/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7857 - loss: 0.4802 - val_accuracy: 0.7712 - val_loss: 0.5245
Epoch 11/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7865 - loss: 0.4743 - val_accuracy: 0.7707 - val_loss: 0.5142
Epoch 12/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7806 - loss: 0.4827 - val_accuracy: 0.7773 - val_loss: 0.5127
Epoch 13/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7850 - loss: 0.4761 - val_accuracy: 0.7759 - val_loss: 0.5213
Epoch 14/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7918 - loss: 0.4622 - val_accuracy: 0.7680 - val_loss: 0.5384
Epoch 15/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7883 - loss: 0.4681 - val_accuracy: 0.7693 - val_loss: 0.5295
Epoch 16/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7906 - loss: 0.4644 - val_accuracy: 0.7759 - val_loss: 0.5265
Epoch 17/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7870 - loss: 0.4694 - val_accuracy: 0.7714 - val_loss: 0.5309
Epoch 18/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7924 - loss: 0.4523 - val_accuracy: 0.7759 - val_loss: 0.5310
Epoch 19/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7931 - loss: 0.4541 - val_accuracy: 0.7725 - val_loss: 0.5366
Epoch 20/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7981 - loss: 0.4477 - val_accuracy: 0.7678 - val_loss: 0.5388
Epoch 21/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7999 - loss: 0.4427 - val_accuracy: 0.7685 - val_loss: 0.5498
Epoch 22/100
890/890 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7990 - loss: 0.4375 - val_accuracy: 0.7736 - val_loss: 0.5404
223/223 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
              precision    recall  f1-score   support

          P1       0.77      0.80      0.79       749
          P2       0.83      0.91      0.87      4274
          P3       0.48      0.28      0.36      1142
          P4       0.75      0.74      0.74       951

    accuracy                           0.78      7116
   macro avg       0.71      0.68      0.69      7116
weighted avg       0.75      0.78      0.76      7116

In [77]:
pd.DataFrame(y_encoded).value_counts()

0      1      2      3
False  True   False  False    21368
       False  True   False     5710
              False  True      4756
True   False  False  False     3745
Name: count, dtype: int64

In [78]:
x_train.shape[1]

51

In [79]:
x_train.shape

(28463, 51)

## Save the model

In [80]:
import joblib

joblib.dump(best_model, 'xgboost_model.joblib')
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [82]:
# Get feature importances from the best XGBoost model
feature_importances = best_model.feature_importances_

# Get the names of the features
feature_names = x.columns

# Create a pandas Series to easily view feature importances
importances_df = pd.Series(feature_importances, index=feature_names)

# Sort the features by importance in descending order
sorted_importances = importances_df.sort_values(ascending=False)

# Display the sorted feature importances
print("Feature Importances (XGBoost):")
print(sorted_importances)

Feature Importances (XGBoost):
enq_L3m                         0.192875
Age_Oldest_TL                   0.129086
pct_PL_enq_L6m_of_ever          0.093160
max_recent_level_of_deliq       0.072255
num_std_12mts                   0.070002
time_since_recent_enq           0.065071
recent_level_of_deliq           0.044350
max_deliq_12mts                 0.030016
num_deliq_6_12mts               0.018069
Age_Newest_TL                   0.015249
num_times_60p_dpd               0.012477
last_prod_enq2_PL               0.011570
GENDER_M                        0.011373
HL_Flag                         0.010522
Home_TL                         0.010236
pct_CC_enq_L6m_of_ever          0.010079
first_prod_enq2_others          0.009982
time_since_recent_payment       0.009511
Secured_TL                      0.009405
last_prod_enq2_ConsumerLoan     0.009328
pct_tl_open_L6M                 0.008992
PL_enq_L12m                     0.008912
Tot_Missed_Pmnt                 0.008822
MARITALSTATUS_Single            0.008675
Unsecured_TL                    0.008342
Other_TL                        0.008141
last_prod_enq2_CC               0.007952
CC_TL                           0.007610
pct_tl_closed_L6M               0.007561
NETMONTHLYINCOME                0.007545
Time_With_Curr_Empr             0.007376
first_prod_enq2_PL              0.007279
first_prod_enq2_CC              0.007037
Tot_TL_closed_L12M              0.006932
CC_enq_L12m                     0.006743
last_prod_enq2_others           0.006661
num_sub_6mts                    0.006041
PL_TL                           0.005878
first_prod_enq2_ConsumerLoan    0.005623
EDUCATION                       0.005303
num_sub                         0.004768
last_prod_enq2_HL               0.004101
num_sub_12mts                   0.003724
num_dbt                         0.002907
first_prod_enq2_HL              0.002457
PL_Flag                         0.000000
num_lss                         0.000000
num_dbt_12mts                   0.000000
CC_Flag                         0.000000
num_lss_12mts                   0.000000
GL_Flag                         0.000000
dtype: float32

In [83]:
%%writefile app.py
import gradio as gr
import pandas as pd
import joblib
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Load the trained model and scaler
try:
    xgb_model = joblib.load('xgboost_model.joblib')
    scaler = joblib.load('scaler.joblib')

    label_encoder = LabelEncoder()
    label_encoder.fit(['P1', 'P2', 'P3', 'P4'])

    description_df = pd.read_excel("Description.xlsx")
    feature_description_mapping = description_df.set_index('Variable Name')['Description'].to_dict()
except FileNotFoundError:
    print("Error: Model, scaler, or description file not found. Please ensure 'xgboost_model.joblib', 'scaler.joblib', and 'Description.xlsx' are in the same directory.")
    exit() # Exit if files are missing

top_10_features = ['enq_L3m', 'Age_Oldest_TL', 'pct_PL_enq_L6m_of_ever', 'max_recent_level_of_deliq', 'num_std_12mts', 'time_since_recent_enq', 'recent_level_of_deliq', 'max_deliq_12mts', 'num_deliq_6_12mts', 'Age_Newest_TL']


def predict_approved_flag_gradio(*args):
    """
    Preprocesses raw input data and predicts the Approved_Flag using a saved XGBoost model.

    Args:
        *args: Input features from the Gradio interface in the order defined by the inputs list.

    Returns:
        str: The predicted Approved_Flag ('P1', 'P2', 'P3', or 'P4').
             Returns an error message if preprocessing or prediction fails.
    """
    if len(args) != len(top_10_features):
        return "Error: Incorrect number of input features provided."

    raw_data = dict(zip(top_10_features, args))

    try:
        # Convert raw_data to a pandas DataFrame
        input_df = pd.DataFrame([raw_data])

        columns_to_be_removed = ['time_since_first_deliquency', 'time_since_recent_delinquency',
                                 'max_delinquency_level', 'max_deliq_6mts', 'CC_utilization',
                                 'PL_utilization', 'max_unsec_exposure_inPct']

        training_columns = ['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'max_deliq_12mts', 'num_times_60p_dpd', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_12mts', 'num_lss', 'num_lss_12mts', 'recent_level_of_deliq', 'CC_enq_L12m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'EDUCATION', 'MARITALSTATUS_Single', 'GENDER_M', 'last_prod_enq2_CC', 'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL', 'last_prod_enq2_others', 'first_prod_enq2_CC', 'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL', 'first_prod_enq2_PL', 'first_prod_enq2_others']

        full_feature_df = pd.DataFrame(0.0, index=[0], columns=training_columns)

        # Populate the full DataFrame with the provided top 10 feature values
        for feature, value in raw_data.items():
             if feature in full_feature_df.columns:
                  if feature == 'EDUCATION':
                       education_mapping = {'OTHERS': 1, 'SSC': 1, '12TH': 2, 'UNDER GRADUATE': 3, 'GRADUATE': 3, 'PROFESSIONAL': 3, 'POST-GRADUATE': 4}
                       full_feature_df[feature] = education_mapping.get(value, 1)
                  elif feature in ['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
                       if feature == 'MARITALSTATUS' and value == 'Single':
                           full_feature_df['MARITALSTATUS_Single'] = 1.0
                       elif feature == 'GENDER' and value == 'M':
                           full_feature_df['GENDER_M'] = 1.0
                       elif feature in ['last_prod_enq2', 'first_prod_enq2']:
                            encoded_col_name = f'{feature}_{value}'
                            if encoded_col_name in full_feature_df.columns:
                                full_feature_df[encoded_col_name] = 1.0
                  else:
                       # For numerical features in top_10
                       full_feature_df[feature] = value

        for col in full_feature_df.columns:
             if full_feature_df[col].dtype != 'object':
                  mean_val = full_feature_df[col][full_feature_df[col] != -99999].mean() if not full_feature_df[col][full_feature_df[col] != -99999].empty else 0
                  full_feature_df[col] = full_feature_df[col].replace(-99999, mean_val)


        # Apply scaling to numerical features using the loaded scaler
        numerical_cols = full_feature_df.select_dtypes(include=np.number).columns.tolist()
        full_feature_df[numerical_cols] = scaler.transform(full_feature_df[numerical_cols])


        # Make prediction
        prediction_encoded = xgb_model.predict(full_feature_df)

        # Decode the prediction
        predicted_flag = label_encoder.inverse_transform(prediction_encoded)

        return predicted_flag[0]

    except Exception as e:
        return f"Error during prediction: {e}"

input_components = []
for feature in top_10_features:
    feature_label = feature_description_mapping.get(feature, feature)

    if feature == 'enq_L3m':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'Age_Oldest_TL':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'pct_PL_enq_L6m_of_ever':
        input_components.append(gr.Number(label=feature_label, minimum=0.0, maximum=1.0))
    elif feature == 'max_recent_level_of_deliq':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'num_std_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'time_since_recent_enq':
        input_components.append(gr.Number(label=feature_label, minimum=-99999, precision=0)) # Keep -99999 handling
    elif feature == 'recent_level_of_deliq':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'max_deliq_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'num_deliq_6_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'Age_Newest_TL':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))

# Create the Gradio interface
iface = gr.Interface(
    fn=predict_approved_flag_gradio,
    inputs=input_components,
    outputs="text",
    title="Approved Flag Prediction App (Top 10 Features)",
    description="Enter the details for the top 10 features to predict the Approved Flag."
)

if __name__ == "__main__":
    print("Gradio interface created. You can launch it using `iface.launch()`")
    iface.launch(share=True)

Writing app.py

# Run App.py

In [87]:
import gradio as gr
import pandas as pd
import joblib
import numpy as np
from sklearn.preprocessing import LabelEncoder

# Load the trained model and scaler
try:
    xgb_model = joblib.load('xgboost_model.joblib')
    scaler = joblib.load('scaler.joblib')
    label_encoder = LabelEncoder()

    label_encoder.fit(['P1', 'P2', 'P3', 'P4'])

    description_df = pd.read_excel("Description.xlsx")
    feature_description_mapping = description_df.set_index('Variable Name')['Description'].to_dict()
except FileNotFoundError:
    print("Error: Model, scaler, or description file not found. Please ensure 'xgboost_model.joblib', 'scaler.joblib', and 'Description.xlsx' are in the same directory.")
    exit() # Exit if files are missing

top_10_features = ['enq_L3m', 'Age_Oldest_TL', 'pct_PL_enq_L6m_of_ever', 'max_recent_level_of_deliq', 'num_std_12mts', 'time_since_recent_enq', 'recent_level_of_deliq', 'max_deliq_12mts', 'num_deliq_6_12mts', 'Age_Newest_TL']


def predict_approved_flag_gradio(*args):
    """
    Preprocesses raw input data and predicts the Approved_Flag using a saved XGBoost model.

    Args:
        *args: Input features from the Gradio interface in the order defined by the inputs list.

    Returns:
        str: The predicted Approved_Flag ('P1', 'P2', 'P3', or 'P4').
             Returns an error message if preprocessing or prediction fails.
    """
    if len(args) != len(top_10_features):
        return "Error: Incorrect number of input features provided."

    raw_data = dict(zip(top_10_features, args))

    try:
        # Convert raw_data to a pandas DataFrame
        input_df = pd.DataFrame([raw_data])

        columns_to_be_removed = ['time_since_first_deliquency', 'time_since_recent_delinquency',
                                 'max_delinquency_level', 'max_deliq_6mts', 'CC_utilization',
                                 'PL_utilization', 'max_unsec_exposure_inPct']

        training_columns = ['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'max_deliq_12mts', 'num_times_60p_dpd', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_12mts', 'num_lss', 'num_lss_12mts', 'recent_level_of_deliq', 'CC_enq_L12m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'EDUCATION', 'MARITALSTATUS_Single', 'GENDER_M', 'last_prod_enq2_CC', 'last_prod_enq2_ConsumerLoan', 'last_prod_enq2_HL', 'last_prod_enq2_PL', 'last_prod_enq2_others', 'first_prod_enq2_CC', 'first_prod_enq2_ConsumerLoan', 'first_prod_enq2_HL', 'first_prod_enq2_PL', 'first_prod_enq2_others']

        full_feature_df = pd.DataFrame(0.0, index=[0], columns=training_columns)

        # Populate the full DataFrame with the provided top 10 feature values
        for feature, value in raw_data.items():
             if feature in full_feature_df.columns:
                  if feature == 'EDUCATION':
                       education_mapping = {'OTHERS': 1, 'SSC': 1, '12TH': 2, 'UNDER GRADUATE': 3, 'GRADUATE': 3, 'PROFESSIONAL': 3, 'POST-GRADUATE': 4}
                       full_feature_df[feature] = education_mapping.get(value, 1)
                  elif feature in ['MARITALSTATUS', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
                       if feature == 'MARITALSTATUS' and value == 'Single':
                           full_feature_df['MARITALSTATUS_Single'] = 1.0
                       elif feature == 'GENDER' and value == 'M':
                           full_feature_df['GENDER_M'] = 1.0
                       elif feature in ['last_prod_enq2', 'first_prod_enq2']:
                            encoded_col_name = f'{feature}_{value}'
                            if encoded_col_name in full_feature_df.columns:
                                full_feature_df[encoded_col_name] = 1.0
                  else:
                       full_feature_df[feature] = value

        for col in full_feature_df.columns:
             if full_feature_df[col].dtype != 'object':
                  mean_val = full_feature_df[col][full_feature_df[col] != -99999].mean() if not full_feature_df[col][full_feature_df[col] != -99999].empty else 0
                  full_feature_df[col] = full_feature_df[col].replace(-99999, mean_val)


        # Apply scaling to numerical features using the loaded scaler
        numerical_cols = full_feature_df.select_dtypes(include=np.number).columns.tolist()
        full_feature_df[numerical_cols] = scaler.transform(full_feature_df[numerical_cols])


        # Make prediction
        prediction_encoded = xgb_model.predict(full_feature_df)

        # Decode the prediction
        predicted_flag = label_encoder.inverse_transform(prediction_encoded)

        return predicted_flag[0]

    except Exception as e:
        return f"Error during prediction: {e}"

input_components = []
for feature in top_10_features:
    feature_label = feature_description_mapping.get(feature, feature)

    if feature == 'enq_L3m':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'Age_Oldest_TL':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'pct_PL_enq_L6m_of_ever':
        input_components.append(gr.Number(label=feature_label, minimum=0.0, maximum=1.0))
    elif feature == 'max_recent_level_of_deliq':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'num_std_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'time_since_recent_enq':
        input_components.append(gr.Number(label=feature_label, minimum=-99999, precision=0)) # Keep -99999 handling
    elif feature == 'recent_level_of_deliq':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'max_deliq_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'num_deliq_6_12mts':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))
    elif feature == 'Age_Newest_TL':
        input_components.append(gr.Number(label=feature_label, minimum=0, precision=0))

# Create the Gradio interface
iface = gr.Interface(
    fn=predict_approved_flag_gradio,
    inputs=input_components,
    outputs="text",
    title="Approved Flag Prediction App",
    description="Enter the details for features to predict the Approved Flag."
)

if __name__ == "__main__":
    print("Gradio interface created. You can launch it using `iface.launch()`")
    iface.launch(share=True)

Gradio interface created. You can launch it using `iface.launch()`
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://0abaf6b90b06458bbb.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Gradio interface created. You can launch it using `iface.launch()`
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://18851fe3fb05186571.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [85]:
# Create a requirements.txt file
%%writefile requirements.txt
gradio
pandas
numpy
xgboost
scikit-learn
joblib
openpyxl # Required to read .xlsx file

Writing requirements.txt